<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="$(find robot_description)/urdf/inertial_macros.xacro"/>
    <xacro:include filename="$(find robot_description)/urdf/parts/base/base.gazebo.xacro"/>

    <xacro:macro name="base" params="length width height mass wheel_radius wheel_pos_z">
        <link name="base_footprint"/>

        <link name="base_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                    <!-- <mesh filename="package://robot_description/meshes/STL/base/base.stl"/> -->
                </geometry>
                <material name="yellow">
                    <color rgba="0.8784 0.6627 0.6627 1.0"/>
                </material>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
            </collision>

            <xacro:inertial_box mass="${mass}" x="${length}" y="${width}" z="${height}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_box>      
        </link>

        <!-- Insert Gazebo reference from base.gazebo.xacro file-->
        <xacro:base_gazebo/>

        <joint name="base_to_footprint" type="fixed">
            <parent link="base_footprint"/>
            <child link="base_link"/>
            <origin xyz="0 0 ${wheel_radius - wheel_pos_z}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>
</robot>
